projectName: pixelaw
nameSpace: staging
appType:
  frontend: webapp
  database: db
  api: api

replicaSet: 1

webappContainerService:
  type: ClusterIP  # {{ .Values.webappContainerService.type }}
  port: 3000       # {{ .Values.webappContainerService.port }}

katanaContainerService:
  type: ClusterIP  # {{ .Values.katanaContainerService.type }}
  port: 5050       # {{ .Values.katanaContainerService.port }}

toriiContainerService:
  type: ClusterIP  # {{ .Values.toriiContainerService.type }}
  port: 8080       # {{ .Values.toriiContainerService.port }}

grpcToriiContainerService:
  type: ClusterIP  # {{ .Values.grpcToriiContainerService.type }}
  port: 50051      # {{ .Values.grpcToriiContainerService.port }} #


domainName: oostvoort.work 

subDomainName: 
  pixelaw: pixelaw.dev.aw                 # {{ .Values.subDomainName.pixelaw }}
  katana: katana.dev.pixelaw.aw           # {{ .Values.subDomainName.katana }}
  torii: torii.dev.pixelaw.aw             # {{ .Values.subDomainName.torii }}
  grpcTorii: grpc.dev.torii.pixelaw.aw    # {{ .Values.subDomainName.grpcTorii }}

dockerImage: oostvoort/pixelaw-dev:latest